# Generated by Django 5.0.2 on 2024-02-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_respostas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='qualificação',
            new_name='qualificacao',
        ),
        migrations.AddField(
            model_name='respostas',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
