# Generated by Django 5.0.2 on 2024-02-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_qualificação_pessoa_qualificacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto_perfil',
            field=models.ImageField(default='usuarios\\static\\ppic.png', upload_to='perfil/'),
        ),
    ]
