# Generated by Django 5.0.2 on 2024-02-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_pessoa_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto_perfil',
            field=models.ImageField(default='usuarios\\static\\ppic.png', upload_to='perfil/'),
        ),
    ]
