# Generated by Django 5.0.2 on 2024-02-25 01:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_post_foto_perfil'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='username',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto_perfil',
            field=models.ImageField(default='usuarios/static/ppic.png', upload_to='perfil/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='usuarios/static/ppic.png', null=True, upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respostas',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='usuarios.post'),
        ),
    ]
